// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDL2BDxeLAPE7swTLLs5PO-NrREodD7ag',
    appId: '1:396899017293:android:b16e994446ab2c331bf204',
    messagingSenderId: '396899017293',
    projectId: 'shalltear-d540c',
    storageBucket: 'shalltear-d540c.appspot.com',
    databaseURL: 'https://shalltear-d540c-default-rtdb.asia-southeast1.firebasedatabase.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1Ic7yR79Fs79albHAg-GNKh4CoUeItg',
    appId: '1:396899017293:ios:97c8655d88c53ded1bf204',
    messagingSenderId: '396899017293',
    projectId: 'shalltear-d540c',
    storageBucket: 'shalltear-d540c.appspot.com',
    iosClientId: '396899017293-r36btghg5eih273ftqn6g3rdch585ol3.apps.googleusercontent.com',
    iosBundleId: 'com.yny.shalltear.shalltear',
  );
}
